lfads_prep:
  window_len: 60
  overlap: 20
  bin_size: 0.010
dynamics_analysis:
  num_dims: 10
  bin_size: 0.030
  keep_unsorted: False
  verbose: True
inspection:
  bin_size: 0.010
  keep_unsorted: True
  verbose: True